Repository VerifiedInc/shared-ui-elements, pull requests merged in 2024-11, with the labels that each got.

#43 fix: date input controlled value state
  src/components/form/DateInput.tsx
Labels: hotfix, 1 min review

#44 fix: Fix date input disabled attribute
  src/components/form/DateInput.tsx
  src/components/form/InputMask.tsx
  src/stories/components/form/DateInput.stories.ts
Labels: hotfix, 1 min review

#45 fix: ssn was clearing first value sent to it when using react hook fo…
  src/components/form/SSNInput.tsx
Labels: 1 min review, single-line

#46 feat: rename date method and remove unused ones
  src/components/form/DateInput.tsx
  src/utils/date.ts
Labels: hotfix, 1 min review

#47 feat: add qr code display component
  package-lock.json
  package.json
  src/components/QRCodeDisplay/index.tsx
  src/components/index.ts
  src/hooks/index.ts
  src/hooks/useQRCode.ts
  src/stories/components/QRCodeDisplay.stories.tsx
Labels: hotfix, 10 min review

#48 Chore/peer deps
  package-lock.json
  package.json
Labels: 1 min review

#49 Chore Bundler and prerelease script
  .gitignore
  package-lock.json
  package.json
  tsconfig.json
  vite.config.ts
Labels: 1 min review

#50 chore: automatic package external deps
  README.md
  vite.config.ts
Labels: 1 min review, single-line

#51 Fix/bundling types
  package-lock.json
  package.json
  tsconfig.json
Labels: 1 min review

#54 Chore/publish scripts
  package-lock.json
  package.json
Labels: hotfix, 1 min review

#55 Chore/publish scripts
  package.json
Labels: 1 min review, single-line

#56 chore: adds npmignore so it publishes the dist folder
  .npmignore
Labels: hotfix, 1 min review

#59 chore: update package name to include 'public'
  package-lock.json
  package.json
Labels: 1 min review

#60 Remix build
  .gitignore
  README.md
  package-lock.json
  package.json
  vite.config.ts
Labels: 1 min review

#61 fix paste otp input
  src/components/form/OTPInput.tsx
Labels: hotfix, 1 min review

#62 fix: remove blur causing maximum call stack error, blur on full otp input
  src/components/form/OTPInput.tsx
Labels: 1 min review, single-line

#63 Snackbar
  package-lock.json
  package.json
  src/components/Snackbar/index.tsx
  src/components/index.ts
  src/index.ts
  tsconfig.json
Labels: 10 min review

#65 fix: remove persist option from Snackbar enqueue function
  src/components/Snackbar/index.tsx
Labels: 1 min review, single-line

#66 Fix snackbar
  src/components/Snackbar/index.tsx
Labels: hotfix, 1 min review

#67 fix: add form control to input base to avoid bad setState
  src/components/form/OTPInput.tsx
Labels: hotfix, 1 min review

#68 More fixes
  package-lock.json
  package.json
  src/components/Banners/Banner.tsx
  src/components/Banners/ExactBirthdayBanner.tsx
  src/components/Banners/ResendPhoneBanner.tsx
  src/components/Banners/TestPhoneNumbersBanner.tsx
  src/components/Banners/index.tsx
  src/components/Snackbar/index.tsx
  src/components/form/DateInput.tsx
  src/components/form/SelectInput.tsx
  src/components/index.ts
  src/stories/components/form/DateInput.stories.ts
  src/utils/date.ts
  src/utils/index.ts
  src/utils/ssn.ts
  src/validations/birthDate.schema.ts
  src/validations/index.ts
  src/validations/ssn.schema.ts
Labels: hotfix, 20 min review

#72 chore: fix peer multi version support
  package-lock.json
  package.json
Labels: hotfix, 1 min review
