Repository VerifiedInc/shared-ui-elements, pull requests merged in 2025-01, with the labels that each got.

#86 feat: add new UI components and stories
  package-lock.json
  package.json
  src/components/buttons/LinkButton.tsx
  src/components/buttons/TextButton.tsx
  src/components/buttons/index.ts
  src/components/form/EmailInput.tsx
  src/components/form/index.ts
  src/components/index.ts
  src/components/terms/AcceptTermsNotice.tsx
  src/components/terms/LegalLink.tsx
  src/components/terms/PrivacyPolicyNotice.tsx
  src/components/terms/index.ts
  src/components/typographies/Paragraph.tsx
  src/components/typographies/SectionHeader.tsx
  src/components/typographies/index.ts
  src/stories/components/buttons/LinkButton.stories.tsx
  src/stories/components/buttons/TextButton.stories.tsx
  src/stories/components/form/EmailInput.stories.tsx
  src/stories/components/terms/PrivacyPolicyNotice.stories.tsx
  src/stories/components/typographies/Paragraph.stories.tsx
  src/stories/components/typographies/SectionHeader.stories.tsx
Labels: hotfix, 20 min review

#88 fix: export missing modules
  src/hooks/index.ts
Labels: 1 min review

#90 fix: use theme as default
  src/components/buttons/LinkButton.tsx
  src/components/buttons/TextButton.tsx
Labels: 1 min review

#91 feat: add date range input
  package-lock.json
  package.json
  src/components/form/DateRangeInput/index.tsx
  src/components/form/DateRangeInput/react-datepicker.css
  src/components/form/DateRangeInput/style.ts
  src/components/form/index.ts
  src/stories/components/form/DateRangeInput.stories.tsx
  src/types/css.d.ts
Labels: hotfix, 20 min review

#92 fix picker dependency
  README.md
  package-lock.json
  package.json
  src/components/form/DateRangeInput/index.tsx
Labels: hotfix, 1 min review

#93 feat: add timezone select input
  src/components/form/TimezoneInput/index.tsx
  src/components/form/TimezoneInput/timezones.json
  src/stories/components/form/TimezoneInput.stories.tsx
Labels: 20 min review

#94 fix: exports timezone input
  src/components/form/index.ts
  src/stories/components/form/TimezoneInput.stories.tsx
Labels: 1 min review

#95 fix: remove box from render
  src/components/form/TimezoneInput/index.tsx
Labels: 1 min review, single-line

#96 feat: add series chart legend
  package-lock.json
  package.json
  src/components/chart/SeriesChartLegend/index.tsx
  src/stories/components/chart/SeriesChartLegend.stories.tsx
Labels: hotfix, 20 min review

#97 feat: add series chart
  src/components/chart/SeriesChart/index.tsx
  src/stories/components/chart/SeriesChart.stories.tsx
  src/stories/components/chart/SeriesChartLegend.stories.tsx
  src/utils/date.ts
Labels: hotfix, 20 min review

#98 fix: export modules
  src/components/chart/index.ts
  src/stories/components/chart/SeriesChart.stories.tsx
  src/stories/components/chart/SeriesChartLegend.stories.tsx
Labels: hotfix, 1 min review

#101 fix: remove log
  src/components/chart/SeriesChartLegend/index.tsx
Labels: 1 min review, single-line

#102 fix: add key prop to top react element renderer
  src/components/chart/SeriesChartLegend/index.tsx
Labels: 1 min review, single-line

#103 feat: add series percentage chart
  src/components/chart/SeriesPercentageChart/index.tsx
  src/components/chart/index.ts
  src/stories/components/chart/SeriesPercentageChart.stories.tsx
  vite.config.mts
Labels: 20 min review

#106 fix: add seconds to input
  src/components/form/DateRangeInput/index.tsx
  src/components/form/DateRangeInput/style.ts
Labels: 1 min review

#108 feat: add simple bar chart
  src/components/chart/SimpleBarChart/index.tsx
  src/components/chart/index.ts
  src/stories/components/chart/SimpleBarChart.stories.tsx
Labels: hotfix, 10 min review

#109 Serie bar chart support
  src/components/chart/SimpleBarChart/index.tsx
  src/stories/components/chart/SimpleBarChart.stories.tsx
Labels: 5 min review

#110 fix: enforce boolean
  src/components/chart/SimpleBarChart/index.tsx
Labels: 1 min review, single-line

#111 add tooltip props
  src/components/chart/SimpleBarChart/index.tsx
  src/components/chart/shared.ts
  src/stories/components/chart/SimpleBarChart.stories.tsx
Labels: hotfix, 5 min review

#112 feat: add error code chart
  src/components/chart/ErrorCodesChart/index.tsx
  src/components/chart/index.ts
  src/stories/components/chart/ErrorCodesChart.stories.tsx
Labels: hotfix, 10 min review

#114 feat(PieChart): add needle indicator and enhance chart customization
  src/components/chart/PieChart/index.tsx
  src/components/chart/PieChart/renderActiveShape.tsx
  src/components/chart/PieChart/renderNeedle.tsx
  src/components/chart/SimpleLegend/index.tsx
  src/stories/components/chart/PieChart.stories.tsx
Labels: hotfix, 20 min review

#115 risk score chart
  src/components/chart/PieChart/index.tsx
  src/components/chart/PieChart/renderActiveShape.tsx
  src/components/chart/PieChart/renderNeedle.tsx
  src/components/chart/RiskScorePieChart/index.tsx
  src/components/chart/index.ts
  src/stories/components/chart/PieChart.stories.tsx
  src/stories/components/chart/RiskScorePieChart.stories.tsx
Labels: hotfix, 10 min review

#116 feat: add risk score bar chart
  src/components/chart/RiskScoreBarChart/index.tsx
  src/components/chart/SimpleBarChart/index.tsx
  src/stories/components/chart/RiskScoreBarChart.stories.tsx
Labels: hotfix, 10 min review

#117 refactor: update terms
  src/components/chart/RiskScoreBarChart/index.tsx
Labels: 1 min review, single-line

#118 fix: replace json stringify with label uniqueness falling back to index
  src/components/chart/SimpleBarChart/index.tsx
Labels: 1 min review, single-line

#120 feat: add allActive prop display pie detail
  src/components/chart/PieChart/index.tsx
  src/components/chart/PieChart/renderActiveShape.tsx
  src/components/chart/RiskScorePieChart/index.tsx
  src/stories/components/chart/PieChart.stories.tsx
Labels: hotfix, 1 min review

#121 fix: omit hidden slices info
  src/components/chart/PieChart/index.tsx
Labels: hotfix, 1 min review

#122 fix: filter out if value is zero keeping index reference
  src/components/chart/PieChart/index.tsx
Labels: hotfix, 1 min review

#123 feat: make threshold configurable
  src/components/chart/ErrorCodesChart/index.tsx
Labels: hotfix, 1 min review

#124 feat: Add reason code chart
  src/components/chart/ReasonCodesChart/index.tsx
  src/components/chart/index.ts
  src/stories/components/chart/ReasonCodesChart.stories.tsx
Labels: hotfix, 10 min review

#126 fix: access window within client side hook
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldPhoneInput.tsx
Labels: 1 min review, single-line

#127 feat: make selectable credentials optional
  src/components/form/OneClickForm/components/DataField/DataFieldCheckbox.tsx
  src/components/form/OneClickForm/contexts/one-click-form-options.context.tsx
  src/stories/components/form/OneClickForm.stories.tsx
Labels: hotfix, 1 min review

#128 feat: add fillEmptyByQueryParam option to OneClickForm
  src/components/form/OneClickForm/components/CredentialsDisplay/utils/getLastPathName.ts
  src/components/form/OneClickForm/components/CredentialsDisplay/utils/index.ts
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldSelectInput.tsx
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldTextInput.tsx
  src/components/form/OneClickForm/contexts/one-click-form-options.context.tsx
  src/components/form/OneClickForm/hooks/useCanFillByQueryParam.ts
  src/stories/components/form/OneClickForm.stories.tsx
Labels: 5 min review
