Repository VerifiedInc/shared-ui-elements, pull requests merged in 2025-02, with the labels that each got.

#129 fix loop default value
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldSelectInput.tsx
  src/components/form/OneClickForm/components/DataField/observables.ts
  src/stories/components/form/OneClickForm.stories.tsx
Labels: 10 min review

#131 fix: refactor buildDataFieldValue to prevent child of child item schema to be included in the parent list
  src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts
  src/stories/components/CredentialRequestsEditor.stories.tsx
Labels: 1 min review

#132 fix: remove null type
  src/components/CredentialRequestsEditor/utils/buildDataFieldValue.ts
Labels: 1 min review, single-line

#134 feat: make autocomplete a prop
  src/components/form/OTPInput.tsx
Labels: 1 min review, single-line

#135 feat: support integration type on 1-click percentage chart
  src/components/chart/SeriesChart/index.tsx
  src/components/chart/SeriesChartLegend/index.tsx
  src/stories/components/chart/SeriesChart.stories.tsx
  src/stories/components/chart/SeriesChartLegend.stories.tsx
Labels: 1 min review, approve

#136 Strip chart logic
  package-lock.json
  package.json
  src/components/BrandFilterInput/BrandFilterInput.hook.ts
  src/components/BrandFilterInput/index.tsx
  src/components/BrandFilterInput/types.ts
  src/components/chart/EmptyChartSection.tsx
  src/components/chart/LoadingChartSection.tsx
  src/components/chart/OneClickPercentageChart/OneClickPercentageChart.tsx
  src/components/chart/OneClickPercentageChart/index.ts
  src/components/chart/SeriesChart/index.tsx
  src/components/chart/index.ts
  src/components/chart/monthly-billable-signups/MonthlyBillableSignupsTable.tsx
  src/components/chart/monthly-billable-signups/index.ts
  src/components/chart/monthly-billable-signups/monthlyBillableSignupsDataMapper.ts
  src/components/chart/one-click-time-series/OneClickOverTimeChart.tsx
  src/components/chart/one-click-time-series/OneClickTimeSeriesDataMapper.ts
  src/components/chart/one-click-time-series/index.ts
  src/components/chart/styles.ts
  src/components/index.ts
  src/components/typographies/SectionDescription.tsx
  src/components/typographies/SectionTitle.tsx
  src/utils/index.ts
  src/utils/string/formatKebabToPretty.ts
  src/utils/string/index.ts
  src/utils/uuidColor.ts
Labels: 30 min review, approve

#137 chore: call EmptyChartSection and LoadingChartSection
  src/components/chart/monthly-billable-signups/MonthlyBillableSignupsTable.tsx
Labels: 1 min review, single-line

#138 fix: import name
  src/components/chart/monthly-billable-signups/index.ts
Labels: 1 min review, single-line, approve

#140 Dashboard changes
  package-lock.json
  package.json
  src/components/BrandFilterInput/BrandFilterInput.hook.ts
  src/components/BrandFilterInput/index.tsx
  src/components/BrandFilterInput/types.ts
  src/components/chart/MetricLastUpdated.tsx
  src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTable.tsx
  src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTableDataMapper.ts
  src/components/chart/MonthlySignupsOverviewTable/index.ts
  src/components/chart/OneClickOverTimeChart/OneClickOverTimeChart.tsx
  src/components/chart/OneClickOverTimeChart/OneClickTimeSeriesDataMapper.ts
  src/components/chart/OneClickOverTimeChart/index.ts
  src/components/chart/OneClickPercentageChart/OneClickPercentageChart.tsx
  src/components/chart/SeriesChart/index.tsx
  src/components/chart/SeriesChartLegend/index.tsx
  src/components/chart/SignupBigNumbers/SignupBigNumbers.tsx
  src/components/chart/SignupBigNumbers/SignupBigNumbersMapper.ts
  src/components/chart/SignupBigNumbers/index.ts
  src/components/chart/index.ts
  src/components/chart/monthly-billable-signups/index.ts
  src/components/form/OneClickForm/utils/date.ts
  src/components/index.ts
  src/stories/components/chart/MonthlySignupsOverviewTable.stories.tsx
  src/stories/components/chart/SeriesChart.stories.tsx
  src/stories/components/chart/SignupsBigNumbers.stories.tsx
  src/stories/components/form/BrandFilterInput.stories.tsx
  src/utils/number/formatters.ts
Labels: 30 min review, approve

#141 chore: export phone utils
  vite.config.mts
Labels: 1 min review, single-line

#142 fix: remove default color and integration type checking
  src/components/chart/OneClickOverTimeChart/OneClickTimeSeriesDataMapper.ts
Labels: 1 min review

#143 feat: fix charts to make sure they render 1-click successes when ther…
  src/components/chart/OneClickOverTimeChart/OneClickTimeSeriesDataMapper.ts
  src/components/chart/SeriesPercentageChart/index.tsx
  src/stories/components/chart/SeriesChart.stories.tsx
  src/stories/components/chart/SeriesPercentageChart.stories.tsx
Labels: 5 min review

#144 feat: add navigator online state and resize observer hook
  src/hooks/index.ts
  src/hooks/useNavigatorOnline.ts
  src/hooks/useResizeObserver.ts
  src/stories/hooks/useNavigatorOnline.stories.tsx
  src/stories/hooks/useResizeObserver.stories.tsx
Labels: 20 min review, approve

#146 chore: add animated height component
  src/components/animation/AnimatedHeight.tsx
  src/components/animation/index.ts
  src/stories/components/animation/AnimatedHeight.stories.tsx
Labels: 10 min review

#147 Update wrap promise type
  src/utils/wrapPromise.ts
  vite.config.mts
Labels: 1 min review, approve

#148 Remove default brand limit for brand filter
  package-lock.json
  package.json
  src/components/BrandFilterInput/BrandFilterInput.hook.ts
  src/components/BrandFilterInput/index.tsx
  src/components/chart/SeriesPercentageChart/index.tsx
  src/utils/uuidColor.ts
Labels: 1 min review, approve

#149 fix: export utils and fix wrapPromise path module
  src/utils/wrapPromise/index.ts
  vite.config.mts
Labels: 1 min review

#150 Refactor existing charts
  src/components/chart/ErrorCodesChart/index.tsx
  src/components/chart/ReasonCodesChart/index.tsx
  src/components/chart/RiskScoreBarChart/index.tsx
  src/components/chart/RiskScorePieChart/index.tsx
  src/stories/components/chart/ErrorCodesChart.stories.tsx
  src/stories/components/chart/ReasonCodesChart.stories.tsx
  src/stories/components/chart/RiskScoreBarChart.stories.tsx
  src/stories/components/chart/RiskScorePieChart.stories.tsx
Labels: 20 min review

#151 fix: increase threshold and make an offset to prevent being overflown
  src/components/chart/ErrorCodesChart/index.tsx
  src/components/chart/ReasonCodesChart/index.tsx
Labels: hotfix, 1 min review

#152 fix: prevent duplicated key to render
  src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTable.tsx
  src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTableDataMapper.ts
  src/stories/components/chart/MonthlySignupsOverviewTable.stories.tsx
Labels: hotfix, 1 min review

#153 fix: prevent duplicated key warning
  src/components/chart/SeriesChartLegend/index.tsx
Labels: 1 min review, single-line

#154 chore: add powered by component
  src/components/verified/OneClickPoweredByVerified.tsx
  src/stories/components/OneClickPoweredByVerified.stories.tsx
Labels: 20 min review

#155 fix: export missing component
  src/components/verified/index.ts
Labels: 1 min review, single-line

#157 feat: support onBlur
  src/components/form/PhoneInput.tsx
  src/stories/components/form/PhoneInput.stories.tsx
Labels: 1 min review, approve

#158 fix: add correct svg paths
  src/components/verified/OneClickPoweredByVerified.tsx
Labels: 10 min review, single-line, approve

#159 chore: document phone utils
  src/components/verified/OneClickPoweredByVerified.tsx
  src/stories/utils/phone.stories.tsx
Labels: 10 min review

#161 fix(OTPInput): sync props error
  src/components/form/OTPInput.tsx
Labels: 1 min review, single-line

#162 feat(DateInput): added date picker
  src/components/form/DateInput.tsx
  src/components/form/DateInput/index.tsx
  src/components/form/DateRangeInput/index.tsx
  src/stories/components/form/DateInput.stories.ts
  src/styles/lib/react-datepicker.css
Labels: 20 min review

#163 fix(DateInput): Added new prop to vertical align picker preventing o…
  src/components/form/DateInput/index.tsx
  src/stories/components/form/DateInput.stories.tsx
Labels: hotfix, 1 min review

#165 Feat(DateInput): support default selected date picker
  src/components/form/DateInput/index.tsx
  src/stories/components/form/DateInput.stories.tsx
Labels: 5 min review
