Repository VerifiedInc/shared-ui-elements, pull requests merged in 2025-05, with the labels that each got.

#238 Demo components and timezone input
  package-lock.json
  package.json
  src/components/InvisibleWhen.tsx
  src/components/UI/AdaptativeBox.tsx
  src/components/UI/ContentWithLoader.tsx
  src/components/UI/index.ts
  src/components/dialog/CalendlyDialog.tsx
  src/components/dialog/PersistentDialog.tsx
  src/components/dialog/index.ts
  src/components/form/DateRangeInput/index.tsx
  src/components/form/RadioOption.tsx
  src/components/index.ts
  src/stories/components/dialog/CalendlyDialog.stories.tsx
  src/stories/components/dialog/Dialog.stories.tsx
  src/stories/components/form/RadioOption.stories.tsx
  src/utils/date.ts
Labels: 30 min review, approve

#240 feat(theme): add shadow effect to focused MUI buttons
  src/styles/theme.ts
Labels: 1 min review

#241 refactor: update SdkIntegrationType to use core-service-v2 package
  package-lock.json
  package.json
  src/components/CredentialRequestsEditor/components/DataFieldAccordion.tsx
  src/components/CredentialRequestsEditor/types/sdk.ts
  src/stories/components/CredentialRequestsEditor.stories.tsx
Labels: 1 min review

#242 Fix package lock
  package-lock.json
Labels: hotfix, 1 min review, single-line

#243 Fix package lock
  package-lock.json
  package.json
  src/components/CredentialRequestsEditor/types/sdk.ts
  src/components/chart/SeriesChartLegend/index.tsx
  src/components/chart/SeriesPercentageChartLegend/index.tsx
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/index.tsx
Labels: 1 min review

#244 Fix dependency resolution by updating peer dependencies
  package-lock.json
  package.json
Labels: 1 min review

#245 Enhance OTP input with accessibility and UX improvements
  src/components/form/OTPInput.tsx
  src/styles/theme.ts
Labels: 10 min review

#246 Update MUI v5 compatibility and enhance input components
  package-lock.json
  package.json
  src/components/__for-stories/Iframe.tsx
  src/components/__for-stories/IframeContent.tsx
  src/components/__for-stories/index.tsx
  src/components/chart/SeriesChartLegend/index.tsx
  src/components/chart/SeriesPercentageChartLegend/index.tsx
  src/components/form/BasePhoneInput.tsx
  src/components/form/OTPInput.tsx
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/index.tsx
  src/stories/components/form/OTPInput.stories.tsx
Labels: 30 min review

#247 Lower motion peer dependency and fix component type exports
  package-lock.json
  package.json
  src/components/animation/motions.ts
Labels: 1 min review, approve

#248 Fix framer-motion API usage by replacing deprecated motion.create
  src/components/animation/motions.ts
Labels: 1 min review, single-line

#249 Simplify type casting in motion components
  src/components/animation/motions.ts
Labels: 1 min review, single-line

#250 Enhance form accessibility and fix UI component issues
  package-lock.json
  package.json
  src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplay.tsx
  src/components/form/OneClickForm/components/CredentialsDisplay/components/EditModeButton.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldAtomic.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldComposite.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/index.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldLabel.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldRootStack.tsx
  src/components/form/OneClickForm/components/DataField/formats/DataFieldText.tsx
Labels: 1 min review, approve

#251 Optimize Address Input component performance and validation
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/hook.ts
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldAddressInput/index.tsx
Labels: 1 min review
