Repository VerifiedInc/shared-ui-elements, pull requests merged in 2025-03, with the labels that each got.

#172 fix form
  src/components/form/DateInput/index.tsx
  src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplay.tsx
  src/components/form/OneClickForm/components/CredentialsDisplay/utils/makeCredentialDisplayInfoList.ts
  src/components/form/OneClickForm/components/DataField/DataFieldComposite.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldHeader/HeaderSelect/index.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldInputModeHeader.tsx
  src/components/form/OneClickForm/components/DataField/DataFieldRootStack.tsx
  src/stories/components/form/OneClickForm.stories.tsx
  src/styles/lib/react-datepicker.css
Labels: 1 min review

#177 fix: make total cost optional
  src/components/chart/MonthlySignupsOverviewTable/MonthlySignupsOverviewTableDataMapper.ts
  src/components/chart/OneClickOverTimeChart/OneClickTimeSeriesDataMapper.ts
Labels: 1 min review

#179 fix(theme): Adjust input sizes and label to center it seamlessly
  src/styles/theme.ts
Labels: 1 min review

#183 feat: remove unhealthy threshold from error codes chart
  src/components/chart/ErrorCodesChart/index.tsx
  src/components/chart/ReasonCodesChart/index.tsx
Labels: 1 min review

#186 Fix multi brand component to debounce values
  package-lock.json
  package.json
  src/components/BrandFilterInput/index.tsx
Labels: hotfix, 1 min review

#189 feat: add legend to percentage chart
  src/components/chart/SeriesPercentageChart/index.tsx
  src/components/chart/SeriesPercentageChartLegend/index.tsx
Labels: 10 min review

#191 fix: increase input width to deal with new font sizes
  src/components/form/DateRangeInput/style.ts
  src/components/form/TimezoneInput/index.tsx
Labels: hotfix, 1 min review

#198 fix: don't show "select live brands" under any grouping
  .storybook/preview.tsx
  src/components/BrandFilterInput/index.tsx
Labels: hotfix, 1 min review

#200 feat: update risk signal charts to check for permission
  src/components/chart/NoRiskSignalsPermissionSection/index.tsx
  src/components/chart/ReasonCodesChart/index.tsx
  src/components/chart/RiskScoreBarChart/index.tsx
  src/components/chart/RiskScorePieChart/index.tsx
Labels: 1 min review, approve

#202 fix(ssn): remove duplicated schema and use the fixed one
  src/components/form/OneClickForm/components/validations/fragments/credentials.ts
Labels: 1 min review

#203 Fix form fields behavior and update Places API integration
  src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplay.tsx
  src/components/form/OneClickForm/components/CredentialsDisplay/CredentialsDisplayContext.tsx
  src/components/form/OneClickForm/components/CredentialsDisplay/utils/extractChildrenFromCredentialFieldSet.ts
  src/components/form/OneClickForm/components/CredentialsDisplay/utils/hasMandatoryCredentialRequests.ts
  src/components/form/OneClickForm/components/CredentialsDisplay/utils/index.ts
  src/components/form/OneClickForm/components/DataField/inputs/DataFieldDateInput.tsx
  src/stories/components/form/OneClickForm.stories.tsx
Labels: 1 min review

#207 fix: add correct position
  src/components/form/OneClickForm/components/CredentialsDisplay/components/EditModeButton.tsx
Labels: 1 min review, single-line

#208 fix: add ignore rule to css padding for text area
  src/styles/theme.ts
Labels: 1 min review, single-line
